/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CivitasJuego;
import civitas.OperacionInmobiliaria;
import civitas.OperacionJuego;
import controladorCivitas.Respuesta;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import vistaTextualCivitas.Vista;

/**
 *
 * @author jorgelerre
 */
public class CivitasView extends javax.swing.JFrame implements Vista{
    
    CivitasJuego juego;
    /**
     * Creates new form CivitasView
     */
    public CivitasView() {
        initComponents();
    }
    
    public void SetCivitasJuego(CivitasJuego juego){
        this.juego = juego;
        this.setVisible(true);
    }
    
    
    //METODOS DE VISTA
    @Override
    public void actualiza(){
        this.actualizaJugadorActual();
        this.actualizaCasillaActual();
        
        repaint();
        revalidate();
    }
    
    private void actualizaJugadorActual(){
        jugadorActualPanel.setJugador(juego.getJugadorActual());
    }
    
    private void actualizaCasillaActual(){
        //Actualiza Casilla Actual
        int numCasillaActual = juego.getJugadorActual().getCasillaActual();
        Casilla casillaActual = juego.getTablero().getCasilla(numCasillaActual);
        casillaActualPanel.removeAll();
        JPanel casillaActualSubpanel;
        if(casillaActual.getClass() == CasillaCalle.class){
            casillaActualSubpanel = new PropiedadPanel();
            ((PropiedadPanel)casillaActualSubpanel).setPropiedad((CasillaCalle)casillaActual);
        }
        else{
            casillaActualSubpanel = new CasillaPanel();
            ((CasillaPanel)casillaActualSubpanel).setCasilla(casillaActual);
        }
        casillaActualPanel.add(casillaActualSubpanel);
        
    }

    @Override
    public void pausa(){
        int val= JOptionPane.showConfirmDialog(null, "¿Continuar?", 
                "Siguiente paso", JOptionPane.YES_NO_OPTION);
        if (val==1)
            System.exit(0);
    }

    @Override
    public Respuesta comprar(){
    
        return null;
    
    }

    @Override
    public OperacionInmobiliaria elegirOperacion(){
    
        return null;
    
    }

    @Override
    public int elegirPropiedad(){
    
        return 0;
    
    }

    @Override
    public void mostrarSiguienteOperacion(OperacionJuego operación){
        campoOperacionSiguiente.setText(operación.toString());
        if(operación == OperacionJuego.AVANZAR){
            Dado.createInstance(this);
        }
        
        repaint();
        revalidate();
    }

    @Override
    public void mostrarEventos(){
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jugadorActualPanel = new GUI.JugadorPanel();
        labelJugadorActual1 = new javax.swing.JLabel();
        casillaActualPanel = new javax.swing.JPanel();
        labelJugadorActual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoOperacionSiguiente = new javax.swing.JTextArea();
        labelOperacionSiguiente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setText("Civitas");

        jugadorActualPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelJugadorActual1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelJugadorActual1.setText("Jugador Actual");

        casillaActualPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        labelJugadorActual.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelJugadorActual.setText("Casilla Actual");
        labelJugadorActual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        campoOperacionSiguiente.setEditable(false);
        campoOperacionSiguiente.setColumns(20);
        campoOperacionSiguiente.setRows(5);
        jScrollPane1.setViewportView(campoOperacionSiguiente);

        labelOperacionSiguiente.setText("Operación Siguiente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(labelJugadorActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(casillaActualPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(titulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelOperacionSiguiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)))
                .addComponent(jugadorActualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelJugadorActual1)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(labelJugadorActual1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jugadorActualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelJugadorActual)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casillaActualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelOperacionSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea campoOperacionSiguiente;
    private javax.swing.JPanel casillaActualPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private GUI.JugadorPanel jugadorActualPanel;
    private javax.swing.JLabel labelJugadorActual;
    private javax.swing.JLabel labelJugadorActual1;
    private javax.swing.JLabel labelOperacionSiguiente;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
